import { TimelineProps } from "./timeline_interface";

export const timelines: TimelineProps[] = [
  {
    title: "CISSA Codebrew Hackathon 2024",
    description: "A Hackathon event hosted by CISSA at UniMelb",
    date: "04 Apr 2024 ~ 07 Apr 2024",
    url: "cissa-codebrew-hackathon-2024",
    icon: "codebrew-icon.svg",
    type: "disabled",
  },
  {
    title: "Foundation of Computing Project 1",
    description: "Vaccumator: Exploring about path-finding algorithm",
    date: "16 Apr 2024 ~ 26 Apr 2024",
    url: "foc-project-1",
    icon: "unimelb-icon.jpg",
    type: "hidden",
  },
  {
    title: "Foundation of Computing Project 2",
    description: "Zoomerbinies: Grouping objects by different constraints",
    date: "1 May 2024 ~ 17 May 2024",
    url: "foc-project-2",
    icon: "unimelb-icon.jpg",
    type: "hidden",
  },
  {
    title: "VICHACK 2024",
    description: "Hackathon",
    date: "09 Aug 2024 ~ 18 Aug 2024",
    url: "vichack-2024",
    icon: "vichack.png",
    type: "disabled",
  },
  {
    title: "Foundation of Algorithm Project 1",
    description: "Forging the basics of C",
    date: "28 Aug 2024 ~ 13 Sep 2024",
    url: "foa-project-1",
    icon: "unimelb-icon.jpg",
    type: "hidden",
  },
  {
    title: "Foundation of Algorithm Project 2",
    description: "Game of Life",
    date: "18 Sep 2024 ~ 11 Oct 2024",
    url: "foa-project-1",
    icon: "unimelb-icon.jpg",
    type: "hidden",
  },
  {
    title: "Engineering Line Following Project",
    description: "Implementing line following algorithm and PID control",
    date: "26 Jul 2024 ~ 18 Oct 2024",
    url: "emd-project",
    icon: "unimelb-icon.jpg",
    type: "hidden",
  },
  {
    title: "Interaction Design Project",
    description: "Creating prototypes about tabletop game using Figma",
    date: "23 Jul 2024 ~ 28 Oct 2024",
    url: "interaction-design-project",
    icon: "unimelb-icon.jpg",
    type: "hidden",
  },
  {
    title: "OpenGL Projection",
    description: "Using linear algebra projection to project a shape",
    date: "14 Oct 2024",
    url: "opengl-projection",
    icon: "shape_2.png",
    type: "enabled",
  },
];
